export const TOP_SELLING_PRODUCTS_REQUESTED = 'TOP_SELLING_PRODUCTS_REQUESTED';
export const TOP_SELLING_PRODUCTS_FETCHED_SUCCESSFULLY = 'TOP_SELLING_PRODUCTS_FETCHED_SUCCESSFULLY';
export const TOP_SELLING_PRODUCTS_FETCH_FAILED = 'TOP_SELLING_PRODUCTS_FETCH_FAILED';

export const PRODUCT_LIST_REQUESTED = 'PRODUCT_LIST_REQUESTED';
export const PRODUCT_LIST_FETCHED_SUCCESSFULLY = 'PRODUCT_LIST_FETCHED_SUCCESSFULLY';
export const PRODUCT_LIST_FETCH_FAILED = 'PRODUCT_LIST_FETCH_FAILED';

export const PRODUCT_REQUESTED = 'PRODUCT_REQUESTED';
export const PRODUCT_FETCHED_SUCCESSFULLY = 'PRODUCT_FETCHED_SUCCESSFULLY';
export const PRODUCT_FETCH_FAILED = 'PRODUCT_FETCH_FAILED';

export const PRODUCT_ADDED_TO_CART = 'PRODUCT_ADDED_TO_CART';
export const PRODUCT_REMOVED_FROM_CART = 'PRODUCT_REMOVED_FROM_CART';