// @flow

export const TOP_SELLING_PRODUCTS_REQUESTED: string = 'TOP_SELLING_PRODUCTS_REQUESTED';
export const TOP_SELLING_PRODUCTS_FETCHED_SUCCESSFULLY: string = 'TOP_SELLING_PRODUCTS_FETCHED_SUCCESSFULLY';
export const TOP_SELLING_PRODUCTS_FETCH_FAILED: string = 'TOP_SELLING_PRODUCTS_FETCH_FAILED';

export const PRODUCT_LIST_REQUESTED: string = 'PRODUCT_LIST_REQUESTED';
export const PRODUCT_LIST_FETCHED_SUCCESSFULLY: string = 'PRODUCT_LIST_FETCHED_SUCCESSFULLY';
export const PRODUCT_LIST_FETCH_FAILED: string = 'PRODUCT_LIST_FETCH_FAILED';

export const PRODUCT_REQUESTED: string = 'PRODUCT_REQUESTED';
export const PRODUCT_FETCHED_SUCCESSFULLY: string = 'PRODUCT_FETCHED_SUCCESSFULLY';
export const PRODUCT_FETCH_FAILED: string = 'PRODUCT_FETCH_FAILED';

export const PRODUCT_ADDED_TO_CART: string = 'PRODUCT_ADDED_TO_CART';
export const PRODUCT_REMOVED_FROM_CART: string = 'PRODUCT_REMOVED_FROM_CART';

export const CART_POPUP_SHOW: string = 'CART_POPUP_SHOW';
export const CART_POPUP_HIDE: string = 'CART_POPUP_HIDE';

export const NOTIFICATION_ADD: string = 'NOTIFICATION_ADD';
export const NOTIFICATION_REMOVE: string = 'NOTIFICATION_REMOVE';
export const NOTIFICATION_SHOW: string = 'NOTIFICATION_SHOW';
export const NOTIFICATION_HIDE: string = 'NOTIFICATION_HIDE';

export const LAST_VIEWED_PRODUCT_ADD = 'LAST_VIEWED_PRODUCT_ADD';

export const LOCALE_CHANGE:string = 'LOCALE_CHANGE';

export const GET_CITY: string = 'GET_SITY';